name: Publish Dev Container Templates

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Template to GHCR
        run: |
          devcontainer templates publish \
            ./src \
            --registry ghcr.io \
            --namespace ${{ github.repository }}
